server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    serviceA:
      path: /greetings-api/**
      serviceId: greeting-service
    serviceB:
      path: /tasks-api/**
      serviceId: task-service